id: c3fbe9d92aeb401aac1e4bccc773261f
initial_creation_type: ocr
source_metadata:
  volumes:
    87d28b5dae86489c96437d2209eb578b:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: བྱང་ཆུབ་སྤྱོད་པའི་སྒྲོན་མ།
      total_pages: 1902
      volume_number: 26
